#!/bin/bash
grep -P -o " [0-9]+ " newnames3.txt > kraken_taxids.txt
sed -i 's/ //g' kraken_taxids.txt
sed -i -e 's/^/>kraken:taxid|/' kraken_taxids.txt
awk 'NR%2==0' MARES_BAR_BOLD_NCBI_sl_reformatted.fasta | paste -d'\n' kraken_taxids.txt - > MARES_BAR_BOLD_NCBI_sl_kraken.fasta
kraken2-build --download-taxonomy --db mares
kraken2-build --add-to-library Marine_Euk_BOLD_NCBI_sl_kraken.fasta --db mares
kraken2-build --build --db mares
